@urlLocal = http://localhost:6595/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTVkODQ2YWVjNWExNzUxMDU1NDY0NWUiLCJub21icmUiOiJQYWJsbyBHYWJyaWVsIiwiZW1haWwiOiJ3aWVzcGFibG9AZ21haWwuY29tIiwiZGlyZWNjaW9uIjoiQXJhIEJhaGlhIFBhcmFpc28gMjY1IiwidGVsZWZvbm8iOjI5NjQ0NjkxNTcsImFwZWxsaWRvIjoiV2llcyIsImlhdCI6MTcwMTAyOTQ2MywiZXhwIjoxNzAxMDU4MjYzfQ.qzxx_O1Eh-oODLADjdYhP8rV7-OdZIeWv8T9DbaPPhE


# login user
POST {{urlLocal}}/login
Content-Type: application/json

{
    "email": "wiespablo@gmail.com", 
    "password" : "algodecente"
}

###
# register user

POST {{urlLocal}}/register HTTP/1.1
Content-Type: application/json

{
    "nombre": "choco",
    "apellido": "Wies",
    "telefono": 2964469157 ,
    "direccion": "Ara Bahia Paraiso 265",
    "email": "choco@gmail.com",
    "password": "algodecente"
}

###


## registrar evento

POST {{urlLocal}}/evento/crear HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "tematica": "Halowen",
    "lugar": "El Bosque",
    "fecha": "2023-12-01" ,
    "direccion": "Ara Bahia Paraiso 265",
    "hora": "21:00",
    "anfitrion": "655d846aec5a17510554645e",
    "lista_invitados": [  
        {
            "invitado": "655d859f7b6c738dc85de5cc",
            "estado": "pendiente"
        },
        {
            "invitado": "655d861d672e6b8e222c35d7",
            "estado": "pendiente"
        },
        {
            "invitado": "656272a70bfce5a89653686f",
            "estado": "pendiente"
        }
    ]
}

###

